name: Manual Test Distribution

on:
  workflow_dispatch:

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout master branch
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle Cache
      # - name: Gradle Cache
      #   uses: gradle/actions/setup-gradle@v3

      # 4. Decode Keystore
      - name: Decode Keystore
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        run: echo "$RELEASE_KEYSTORE_BASE64" | base64 --decode > app/release.keystore

      # 5. Create Keystore Properties
      - name: Create Keystore Properties
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo "storeFile=release.keystore" > app/keystore.properties
          echo "storePassword=$KEY_STORE_PASSWORD" >> app/keystore.properties
          echo "keyAlias=$KEY_ALIAS" >> app/keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> app/keystore.properties

      # 6. Setup Google Services
      - name: Setup Google Services
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json

      # 7. Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 8. Build and Upload to Firebase App Distribution
      - name: Build and Upload Debug to Firebase
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ./gradlew :app:assembleDebug && ./gradlew :app:appDistributionUploadDebug
